<div class="navbar-text">
	<a href="/switch-language/it_IT"><span class="flag-icon flag-icon-it"></span></a>
	<a href="/switch-language/en_EN"><span class="flag-icon flag-icon-gb"></span></a>
	<a href="/switch-language/de_DE"><span class="flag-icon flag-icon-de"></span></a>
</div>
<form class="navbar-form" role="search">
	<div class="input-group">
		<input class="form-control" placeholder="Search" name="srch-term"
			id="srch-term" type="text">
		<div class="input-group-btn">
			<button class="btn btn-default" type="submit">
				<i class="glyphicon glyphicon-search"></i>
			</button>
		</div>
	</div>
</form>